# Generated by Django 3.2.9 on 2021-11-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20211103_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='kind',
            name='k_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='t_id',
        ),
    ]
